### ISSUE TITLE
Checklist: First release by Microsoft

### ISSUE THREAD

**Issue by CsCherrYY** [badsyntax/vscode-gradle#1003]
- [x] Release 3.6.2 in marketplace manually (local bits)
- [x] Release 3.6.2 in Github 
- [x] Change related extension info #901
- [x] Release 3.7.0 with Pipeline (RC pipeline bits)
- [x] Release 3.7.0 in Github
- [x] Modify Changelog including changes in 3.6.2 and 3.7.0 https://github.com/microsoft/vscode-gradle/pull/1011
